type = "canvas"
version = 2

[canvas]
comments = []
edges = []

[[canvas.nodes]]
udfName = "Folder_1"
x = -888.8729738265376
y = 355
zIndex = 1
width = 1656
height = 1190
type = "udf-folder"
title = "Folder_1"
folderName = "Folder_1"
folderColor = "#9370DB40"
childUdfOrder = ["html_1", "widget_1", "udf_1"]

[[canvas.nodes]]
udfName = "udf_1"
x = 40
y = 650
zIndex = 100
width = 700
height = 500
title = "udf_1"
visible = true

[[canvas.nodes]]
udfName = "widget_1"
x = 815
y = 75
zIndex = 101
width = 700
height = 500
title = "widget_1"
visible = true

[[canvas.nodes]]
udfName = "html_1"
x = 40
y = 75
zIndex = 102
width = 700
height = 500
title = "html_1"
visible = true

[[canvas.nodes]]
udfName = "note_1"
x = -1195.2073902751613
y = -175
zIndex = 103
width = 350
height = 250
title = "note_1"
visible = true
textBoxColor = "#A5DD6B"
textBoxGradient = false
textBoxScaleFactor = 1
textBoxAlignment = "left"

[[canvas.nodes]]
udfName = "note_2"
x = -389.04018205084935
y = -382.98245614035096
zIndex = 104
width = 350
height = 250
title = "note_2"
visible = true
textBoxColor = "#FFA767"
textBoxGradient = true
textBoxScaleFactor = 1
textBoxAlignment = "left"

[[canvas.nodes]]
udfName = "note_3"
x = -1239.624210150983
y = 456.0087719298243
zIndex = 105
width = 350
height = 250
title = "note_3"
visible = true
textBoxColor = "#DCC4EB"
textBoxGradient = true
textBoxScaleFactor = 1
textBoxAlignment = "left"

[canvas.viewport]
x = 598.1010247697967
y = 385.29423329240586
zoom = 0.44699112862785145

[canvas.viewportBounds]
minX = -1338.0601682315576
minY = -861.9728862967834
maxX = 865.5629842540371
maxY = 2023.9904301564322
